#!/bin/bash

### BEGIN INIT INFO
# Provides:       cfn-resource-bridge
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts CloudFormation cfn-resource-bridge
# Description:       starts CloudFormation cfn-resource-bridge
### END INIT INFO

PID=/var/run/cfn-resource-bridge.pid
DAEMON=/usr/local/bin/cfn-resource-bridge

. /lib/lsb/init-functions

start() {
        start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --oknodo
}

stop() {
        start-stop-daemon --stop --quiet --pidfile $PID --oknodo
}

restart() {
        stop
        start
}

case "$1" in
  start)
        log_daemon_msg "Starting cfn-resource-bridge"
        start
        log_end_msg $?
        ;;
  stop)
        log_daemon_msg "Stopping cfn-resource-bridge"
        stop
        log_end_msg $?
        ;;
  restart|force-reload|reload)
        restart
        ;;
  status)
        status_of_proc -p $PID "$DAEMON" cfn-resource-bridge
        exit $?
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|reload|force-reload}"
        exit 1
        ;;
esac

exit 0